<?php

$arrLang = array(
    'en' => array(
        'excellent' => 'Excellent',
        'satisfactory' => 'Satisfactory',
        'less_than_satisfactory' => 'Less than Satisfactory',
        'requires_attention' => 'Requires Attention',

        'screen_time_a' => 'Screen Time Management; measures your ability to be able to manage screen time, multitasking and the ability to control yourself in the use of various digital media activities.<br/>A high Screen Time Management score will:<br/>- Balancing physical and virtual reality.<br/>- Self-control in the use of digital technology and understand the various side effects of excessive screen time, multitasking and active use of digital media.<br/>- Be able to manage time and set personal usage limits without letting digital use take over your life.<br/><br/>Congratulations! Your performance in the Screen Time Management category is very good.',
        'screen_time_b' => 'Screen Time Management; measures your ability to be able to manage screen time, multitasking and the ability to control yourself in the use of various digital media activities.<br/>A high Screen Time Management score will:<br/>- Balancing physical and virtual reality.<br/>- Self-control in the use of digital technology and understand the various side effects of excessive screen time, multitasking and active use of digital media.<br/>- Be able to manage time and set personal usage limits without letting digital use take over your life.<br/><br/>You have understood well! Your achievement in the Screen Time Management category is satisfactory.',
        'screen_time_c' => 'Screen Time Management; measures your ability to be able to manage screen time, multitasking and the ability to control yourself in the use of various digital media activities.<br/>A high Screen Time Management score will:<br/>- Balancing physical and virtual reality<br/>- Self-control in the use of digital technology and understand the various side effects of excessive screen time, multitasking and active use of digital media.<br/>- Be able to manage time and set personal usage limits without letting digital use take over your life.<br/><br/>Your performance in this category is unsatisfactory and still needs to be developed in order to be able to manage time well.',
        'screen_time_d' => 'Screen Time Management; measures your ability to be able to manage screen time, multitasking and the ability to control yourself in the use of various digital media activities.<br/>A high Screen Time Management score will:<br/>- Balancing physical and virtual reality<br/>- Self-control in the use of digital technology and understand the various side effects of excessive screen time, multitasking and active use of digital media.<br/>- Be able to manage time and set personal usage limits without letting digital use take over your life.<br/>You are not ready to exercise self-control when using digital media.',

        'privacy_management_a' => 'Privacy Management; measures your ability to handle wisely all personal information shared online to protect your privacy and that of others.<br/>You with a high Privacy Management score will:<br/>- Have the knowledge and skills to handle personal information shared online wisely.<br/>- Have the understanding to ensure and protect the privacy of oneself and others.<br/>- Recognizing that privacy is a fundamental human right.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a good understanding of Privacy Management',
        'privacy_management_b' => 'Privacy Management; measures your ability to handle wisely all personal information shared online to protect your privacy and that of others.<br/>You with a high Privacy Management score will:<br/>- Have the knowledge and skills to handle personal information shared online wisely.<br/>- Have the understanding to ensure and protect the privacy of oneself and others.<br/>- Recognizing that privacy is a fundamental human right.<br/><br/>You have understood well! Your achievement in the Privacy Management category is satisfactory.',
        'privacy_management_c' => 'Privacy Management; measures your ability to handle wisely all personal information shared online to protect your privacy and that of others.<br/>You with a high Privacy Management score will:<br/>- Have the knowledge and skills to handle personal information shared online wisely.<br/>- Have the understanding to ensure and protect the privacy of oneself and others.<br/>- Recognizing that privacy is a fundamental human right.<br/><br/>Your achievements in Privacy Management are unsatisfactory and still need to be developed.',
        'privacy_management_d' => 'Privacy Management; measures your ability to handle wisely all personal information shared online to protect your privacy and that of others.<br/>You with a high Privacy Management score will:<br/>- Have the knowledge and skills to handle personal information shared online wisely.<br/>- Have the understanding to ensure and protect the privacy of oneself and others.<br/>- Recognizing that privacy is a fundamental human right.<br/><br/>Your understanding of the importance of privacy when using digital media is still minimal please improve.',

        'cyberbullying_a' => 'Cyberbullying Management measures your ability to detect cyberbullying situations and handle them wisely.<br/>Those of you with a high Cyberbullying Management score will:<br/>- Have personal discipline to use digital media safely and responsibly.<br/>- Know how to detect cyber threat situations and how to handle situations calmly.<br/>- Know how to handle problems wisely and seek help safely before problems get out of hand.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a solid understanding of Cyberbullying Management so well.',
        'cyberbullying_b' => 'Cyberbullying Management measures your ability to detect cyberbullying situations and handle them wisely.<br/>Those of you with a high Cyberbullying Management score will:<br/>- Have personal discipline to use digital media safely and responsibly.<br/>- Know how to detect cyber threat situations and how to handle situations calmly.<br/>- Know how to handle problems wisely and seek help safely before problems get out of hand.<br/><br/>You have well understood Cyberbullying Management! Your performance in this category is satisfactory.',
        'cyberbullying_c' => 'Cyberbullying Management measures your ability to detect cyberbullying situations and handle them wisely.<br/>Those of you with a high Cyberbullying Management score will:<br/>- Have personal discipline to use digital media safely and responsibly.<br/>- Know how to detect cyber threat situations and how to handle situations calmly.<br/>- Know how to handle problems wisely and seek help safely before problems get out of hand.<br/><br/>Your achievements in Cyberbullying Management are unsatisfactory and still need to be developed.',
        'cyberbullying_d' => 'Cyberbullying Management measures your ability to detect cyberbullying situations and handle them wisely.<br/>Those of you with a high Cyberbullying Management score will:<br/>- Have personal discipline to use digital media safely and responsibly.<br/>- Know how to detect cyber threat situations and how to handle situations calmly.<br/>- Know how to handle problems wisely and seek help safely before problems get out of hand.<br/><br/>Your understanding of Cyberbullying and how to deal with it wisely in digital media is still minimal, please improve it.',


        'digital_citizen_identity_a' => 'Digital Citizen Identity; measure your ability to build and manage a healthy identity and integrity, both online and offline.<br/>Those of you with a high Digital Citizen Identity score will:<br/>- Have a very good understanding of how the digital world works and can use technology with strong confidence.<br/>- Have the knowledge and skills to build and manage a healthy self-identity.<br/>- Realizing how to be a responsible global citizen in the digital space.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a solid understanding of the Digital Citizen Identity Skill so well.',
        'digital_citizen_identity_b' => 'Digital Citizen Identity; measure your ability to build and manage a healthy identity and integrity, both online and offline.<br/>Those of you with a high Digital Citizen Identity score will:<br/>- Have a very good understanding of how the digital world works and can use technology with strong confidence.<br/>- Have the knowledge and skills to build and manage a healthy self-identity.<br/>- Realizing how to be a responsible global citizen in the digital space.<br/><br/>You have a good understanding of Digital Citizen Identity! Your performance in this category is satisfactory.',
        'digital_citizen_identity_c' => 'Digital Citizen Identity; measure your ability to build and manage a healthy identity and integrity, both online and offline.<br/>Those of you with a high Digital Citizen Identity score will:<br/>- Have a very good understanding of how the digital world works and can use technology with strong confidence.<br/>- Have the knowledge and skills to build and manage a healthy self-identity.<br/>- Realizing how to be a responsible global citizen in the digital space.<br/><br/>Your achievements in this Digital Citizen Identity Skill are unsatisfactory and still need to be developed.',
        'digital_citizen_identity_d' => 'Digital Citizen Identity; measure your ability to build and manage a healthy identity and integrity, both online and offline.<br/>Those of you with a high Digital Citizen Identity score will:<br/>- Have a very good understanding of how the digital world works and can use technology with strong confidence.<br/>- Have the knowledge and skills to build and manage a healthy self-identity.<br/>- Realizing how to be a responsible global citizen in the digital space.<br/><br/>Your understanding of a healthy and responsible Digital Citizen Identity on digital media is still minimal; please improve it.',

        'digital_footprint_a' => 'Digital Footprint Management; measure your ability to understand the nature of digital footprints, their real-life consequences and how to manage them responsibly.<br/>Those of you with a high Digital Footprint Management score will:<br/>- Understanding the nature of online communication and knowing that everything said and done online leaves a trail known as a digital footprint.<br/>- Be aware of the persistent nature of digital footprints and their real-life consequences, including creating an unintended impact on your online reputation.<br/><br/>We recommend that you have the skills to manage your digital footprint responsibly.<br/><br/>
        Congratulations! Your performance in this category is very good. Thank you for supporting a solid understanding of Digital Footprint Management well.',
        'digital_footprint_b' => 'Digital Footprint Management; measure your ability to understand the nature of digital footprints, their real-life consequences and how to manage them responsibly.<br/>Those of you with a high Digital Footprint Management score will:<br/>- Understanding the nature of online communication and knowing that everything said and done online leaves a trail known as a digital footprint.<br/>- Be aware of the persistent nature of digital footprints and their real-life consequences, including creating an unintended impact on your online reputation.<br/><br/>We recommend that you have the skills to manage your digital footprint responsibly.<br/><br/>You have a good understanding of Digital Footprint Management! Your performance in this category is satisfactory.',
        'digital_footprint_c' => 'Digital Footprint Management; measure your ability to understand the nature of digital footprints, their real-life consequences and how to manage them responsibly.<br/>Those of you with a high Digital Footprint Management score will:<br/>- Understanding the nature of online communication and knowing that everything said and done online leaves a trail known as a digital footprint.<br/>- Be aware of the persistent nature of digital footprints and their real-life consequences, including creating an unintended impact on your online reputation.<br/><br/>We recommend that you have the skills to manage your digital footprint responsibly.<br/><br/>Your achievements in the Digital Footprint Management category are unsatisfactory and still need to be developed.',
        'digital_footprint_d' => 'Digital Footprint Management; measure your ability to understand the nature of digital footprints, their real-life consequences and how to manage them responsibly.<br/>Those of you with a high Digital Footprint Management score will:<br/>- Understanding the nature of online communication and knowing that everything said and done online leaves a trail known as a digital footprint.<br/>- Be aware of the persistent nature of digital footprints and their real-life consequences, including creating an unintended impact on your online reputation.<br/><br/>We recommend that you have the skills to manage your digital footprint responsibly.<br/><br/>Your understanding of Digital Footprint and how to manage it well on digital media is still minimal; please improve it.',

        'cyber_security_management_a' => 'Cyber Security Management; measure your ability to protect personal data by creating strong passwords and to manage various attacks in cyberspace, namely: SPAM / SCAM / Phishing.<br/>Those of you with a high Cyber Security Management score will:<br/>- Have the ability to recognize and protect yourself and others from various cyber attacks such as: Spam/Scam and Phishing.<br/>- Have practical skills like creating strong passwords and knowing how to protect yourself.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a solid understanding of Cyber Security Management well.',
        'cyber_security_management_b' => 'Cyber Security Management; measure your ability to protect personal data by creating strong passwords and to manage various attacks in cyberspace, namely: SPAM / SCAM / Phishing.<br/>Those of you with a high Cyber Security Management score will:<br/>- Have the ability to recognize and protect yourself and others from various cyber attacks such as: Spam/Scam and Phishing.<br/>- Have practical skills like creating strong passwords and knowing how to protect yourself.<br/><br/>You have a good understanding of Cyber Security Management! Your performance in this category is satisfactory.',
        'cyber_security_management_c' => 'Cyber Security Management; measure your ability to protect personal data by creating strong passwords and to manage various attacks in cyberspace, namely: SPAM / SCAM / Phishing.<br/>Those of you with a high Cyber Security Management score will:<br/>- Have the ability to recognize and protect yourself and others from various cyber attacks such as: Spam/Scam and Phishing.<br/>- Have practical skills like creating strong passwords and knowing how to protect yourself.<br/><br/>Your achievements in the Cyber Security Management category are unsatisfactory and still need to be developed.',
        'cyber_security_management_d' => 'Cyber Security Management; measure your ability to protect personal data by creating strong passwords and to manage various attacks in cyberspace, namely: SPAM / SCAM / Phishing.<br/>Those of you with a high Cyber Security Management score will:<br/>- Have the ability to recognize and protect yourself and others from various cyber attacks such as: Spam/Scam and Phishing.<br/>- Have practical skills like creating strong passwords and knowing how to protect yourself.<br/><br/>Your understanding of the importance of Cyber Security in protecting yourself and others on digital media is still minimal; please improve it.',


        'critical_thinking_a' => 'Critical thinking; measures your ability to distinguish between true and false information, good and harmful content and which online contacts are trustworthy and questionable.<br/>Those of you with a high critical thinking score will:<br/>- Have the knowledge and skills to evaluate information, content and contacts on the Internet wisely.<br/>- Understand the harmful effects of false information, violent content, inappropriate content, and the risks associated with online friends.<br/>- Demonstrate critical thinking when distinguishing between true and false information, good and harmful content and trusted or questionable online contacts.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a strong understanding of Critical Thinking Skills well.',
        'critical_thinking_b' => 'Critical thinking; measures your ability to distinguish between true and false information, good and harmful content and which online contacts are trustworthy and questionable.<br/>Those of you with a high critical thinking score will:<br/>- Have the knowledge and skills to evaluate information, content and contacts on the Internet wisely.<br/>- Understand the harmful effects of false information, violent content, inappropriate content, and the risks associated with online friends.<br/>- Demonstrate critical thinking when distinguishing between true and false information, good and harmful content and trusted or questionable online contacts.<br/><br/>You have well understood the Critical Thinking Skill! Your performance in this category is satisfactory.',
        'critical_thinking_c' => 'Critical thinking; measures your ability to distinguish between true and false information, good and harmful content and which online contacts are trustworthy and questionable.<br/>Those of you with a high critical thinking score will:<br/>- Have the knowledge and skills to evaluate information, content and contacts on the Internet wisely.<br/>- Understand the harmful effects of false information, violent content, inappropriate content, and the risks associated with online friends.<br/>- Demonstrate critical thinking when distinguishing between true and false information, good and harmful content and trusted or questionable online contacts.<br/><br/>Your achievements in the Critical Thinking Skill category are unsatisfactory and still need to be developed.
        ',
        'critical_thinking_d' => 'Critical thinking; measures your ability to distinguish between true and false information, good and harmful content and which online contacts are trustworthy and questionable.<br/>Those of you with a high critical thinking score will:<br/>- Have the knowledge and skills to evaluate information, content and contacts on the Internet wisely.<br/>- Understand the harmful effects of false information, violent content, inappropriate content, and the risks associated with online friends.<br/>- Demonstrate critical thinking when distinguishing between true and false information, good and harmful content and trusted or questionable online contacts.<br/><br/>Your understanding of the importance of Critical Thinking when using digital media is still minimal, please improve.',


        'digital_empathy_a' => 'Digital Empathy; measures your ability to empathize with the needs and feelings of yourself and others online.<br/>You with a high Digital Empathy score will;<br/>- Be sensitive to the needs and feelings of yourself and others online without even having to interact face-to-face.<br/>- Have the ability to build good relationships with parents, teachers and friends online and offline.<br/>- Resist judgmental mindsets online and have the courage to speak up for those who need help.<br/><br/>Congratulations! Your performance in this category is very good. Thank you for supporting a strong understanding of Digital Empathy Skills so well.',
        'digital_empathy_b' => 'Digital Empathy; measures your ability to empathize with the needs and feelings of yourself and others online.<br/>You with a high Digital Empathy score will:<br/>- Be sensitive to the needs and feelings of yourself and others online without even having to interact face-to-face.<br/>- Have the ability to build good relationships with parents, teachers and friends online and offline.<br/>- Resist judgmental mindsets online and have the courage to speak up for those who need help.<br/><br/>You have well grasped the Digital Empathy Skill! Your performance in this category is satisfactory.',
        'digital_empathy_c' => 'Digital Empathy; measures your ability to empathize with the needs and feelings of yourself and others online.<br/>You with a high Digital Empathy score will:<br/>- Be sensitive to the needs and feelings of yourself and others online without even having to interact face-to-face.<br/>- Have the ability to build good relationships with parents, teachers and friends online and offline.<br/>- Resist judgmental mindsets online and have the courage to speak up for those who need help.<br/><br/>Your achievements in the Digital Empathy Skill category are unsatisfactory and still need to be developed.
        ',
        'digital_empathy_d' => 'Digital Empathy; measures your ability to empathize with the needs and feelings of yourself and others online.<br/>You with a high Digital Empathy score will:<br/>- Be sensitive to the needs and feelings of yourself and others online without even having to interact face-to-face.<br/>- Have the ability to build good relationships with parents, teachers and friends online and offline.<br/>- Resist judgmental mindsets online and have the courage to speak up for those who need help.<br/>Your understanding of the importance of Digital Empathy for yourself or others when using digital media is still minimal; please improve.',
    ),
    'id' => array(
        'excellent' => 'Sangat Baik',
        'satisfactory' => 'Memuaskan',
        'less_than_satisfactory' => 'Kurang Memuaskan',
        'requires_attention' => 'Membutuhkan Perhatian',

        'screen_time_a' => 'Manajemen waktu menatap layar; mengukur kemampuan anda untuk dapat mengatur waktu menatap layar, multitasking dan kemampuan untuk mengontrol diri dalam penggunaan bermacam-macam aktivitas media digital. <br/>Skor manajemen waktu menatap layar yang tinggi akan : <br/>- Menyeimbangkan realitas fisik dan virtual <br/>- Mengendalikan diri dalam penggunaan teknologi digital dan memahami berbagai efek samping dari screen time yang berlebihan, multitasking dan penggunaan media digital yang aktif. <br/>- Mampu mengatur waktu dan menetapkan batas penggunaan pribadi tanpa membiarkan penggunaan digital mengambil alih hidup anda.<br/><br/>Selamat! performa anda dalam kategori Screen Time Management ini sangat baik',
        'screen_time_b' => 'Manajemen waktu menatap layar; mengukur kemampuan anda untuk dapat mengatur waktu menatap layar, multitasking dan kemampuan untuk mengontrol diri dalam penggunaan bermacam-macam aktivitas media digital. <br/>Skor manajemen waktu menatap layar yang tinggi akan : <br/>- Menyeimbangkan realitas fisik dan virtual <br/>- Mengendalikan diri dalam penggunaan teknologi digital dan memahami berbagai efek samping dari screen time yang berlebihan, multitasking dan penggunaan media digital yang aktif. <br/>- Mampu mengatur waktu dan menetapkan batas penggunaan pribadi tanpa membiarkan penggunaan digital mengambil alih hidup anda.<br/>Anda telah memahami dengan baik ! Prestasi anda dalam kategori Screen TimeManagement ini memuaskan.',
        'screen_time_c' => 'Management waktu menatap layar mengukur kemampuan anda untuk mengelola waktu menatap layar, multi tasking dan keterlibatan dalam berbagai aktifitas media digital dalam mengontrol diri. Skor management waktu menatap layar yang tinggi akan :<br/>- Menyeimbangkan realitas fisik dan virtual<br/>- Mengendalikan diri dalam penggunaan teknologi digital dan memahami berbagai effek samping dari screen time yang berlebihan, multi tasking dan penggunaanmedia digital yang adiktif.<br/>- Mampu mengatur waktu dan menetapkan batas penggunaan pribadi tanpamembiarkan penggunaan digital mengambil alih hidup anda.<br/><br/>Prestasi anda dalam kategori ini kurang memuaskan dan masih harus dikembangkan agar dapat mengatur manajemen waktu dengan baik.',
        'screen_time_d' => 'Manajemen waktu menatap layar; mengukur kemampuan anda untuk dapat mengatur waktu menatap layar, multitasking dan kemampuan untuk mengontrol diri dalam penggunaan bermacam-macam aktivitas media digital. <br/>Skor manajemen waktu menatap layar yang tinggi akan : <br/>- Menyeimbangkan realitas fisik dan virtual <br/>- Mengendalikan diri dalam penggunaan teknologi digital dan memahami berbagai efek samping dari screen time yang berlebihan, multitasking dan penggunaan media digital yang aktif. <br/>- Mampu mengatur waktu dan menetapkan batas penggunaan pribadi tanpa membiarkan penggunaan digital mengambil alih hidup anda.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',

        'privacy_management_a' => 'Management Privacy; mengukur kemampuan anda untuk menangani dengan bijaksana semua informasi pribadi yang dibagikan secara online untuk melindungi privasi anda dan orang lain. <br/>Anda dengan skor Management Privacy yang tinggi akan : <br/>- Memiliki pengetahuan dan keterampilan untuk menangani informasi pribadi yang dibagikan secara online dengan bijaksana. <br/>- Memiliki pengertian untuk memastikan dan melindungi privasi diri sendiri dan juga orang lain. <br/>- Menyadari bahwa privasi adalah hak asasi manusia yang mendasar.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman Privacy Management dengan baik.',
        'privacy_management_b' => 'Management Privacy; mengukur kemampuan anda untuk menangani dengan bijaksana semua informasi pribadi yang dibagikan secara online untuk melindungi privasi anda dan orang lain. <br/>Anda dengan skor Management Privacy yang tinggi akan : <br/>- Memiliki pengetahuan dan keterampilan untuk menangani informasi pribadi yang dibagikan secara online dengan bijaksana. <br/>- Memiliki pengertian untuk memastikan dan melindungi privasi diri sendiri dan juga orang lain. <br/>- Menyadari bahwa privasi adalah hak asasi manusia yang mendasar.<br/><br/>Anda telah memahami dengan baik ! Prestasi anda dalam kategori Privasi Management memuaskan.',
        'privacy_management_c' => 'Management Privacy; mengukur kemampuan anda untuk menangani dengan bijaksana semua informasi pribadi yang dibagikan secara online untuk melindungi privasi anda dan orang lain. <br/>Anda dengan skor Management Privacy yang tinggi akan : <br/>- Memiliki pengetahuan dan keterampilan untuk menangani informasi pribadi yang dibagikan secara online dengan bijaksana. <br/>- Memiliki pengertian untuk memastikan dan melindungi privasi diri sendiri dan juga orang lain. <br/>- Menyadari bahwa privasi adalah hak asasi manusia yang mendasar.<br/><br/>Prestasi anda dalam Privacy Management ini kurang memuaskan dan masih harus dikembangkan.',
        'privacy_management_d' => 'Management Privacy; mengukur kemampuan anda untuk menangani dengan bijaksana semua informasi pribadi yang dibagikan secara online untuk melindungi privasi anda dan orang lain. <br/>Anda dengan skor Management Privacy yang tinggi akan : <br/>- Memiliki pengetahuan dan keterampilan untuk menangani informasi pribadi yang dibagikan secara online dengan bijaksana. <br/>- Memiliki pengertian untuk memastikan dan melindungi privasi diri sendiri dan juga orang lain. <br/>- Menyadari bahwa privasi adalah hak asasi manusia yang mendasar.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',

        'cyberbullying_a' => 'Management Cyberbullying mengukur kemampuan anda untuk mendeteksi situasi cyberbullying dan menanganinya dengan bijak. <br/>Anda dengan skor Cyberbullying yang tinggi akan : <br/>- Memiliki disiplin pribadi untuk menggunakan media digital secara aman danbertanggung jawab. <br/>- Mengetahui cara mendeteksi situasi ancaman cyber dan cara menangani situasi dengan tenang. <br/>- Mengetahui bagaimana menangani masalah dengan bijaksana dan mencari bantuan dengan aman sebelum masalah menjadi tidak terkendali.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Cyberbullying Management dengan baik.',
        'cyberbullying_b' => 'Management Cyberbullying mengukur kemampuan anda untuk mendeteksi situasi cyberbullying dan menanganinya dengan bijak. <br/>Anda dengan skor Cyberbullying yang tinggi akan : <br/>- Memiliki disiplin pribadi untuk menggunakan media digital secara aman danbertanggung jawab. <br/>- Mengetahui cara mendeteksi situasi ancaman cyber dan cara menangani situasi dengan tenang. <br/>- Mengetahui bagaimana menangani masalah dengan bijaksana dan mencari bantuan dengan aman sebelum masalah menjadi tidak terkendali.<br/><br/>Anda telah memahami dengan baik Cyberbullying Management ! Prestasi anda dalam Kategori ini memuaskan.',
        'cyberbullying_c' => 'Management Cyberbullying mengukur kemampuan anda untuk mendeteksi situasi cyberbullying dan menanganinya dengan bijak. <br/>Anda dengan skor Cyberbullying yang tinggi akan : <br/>- Memiliki disiplin pribadi untuk menggunakan media digital secara aman danbertanggung jawab. <br/>- Mengetahui cara mendeteksi situasi ancaman cyber dan cara menangani situasi dengan tenang. <br/>- Mengetahui bagaimana menangani masalah dengan bijaksana dan mencari bantuan dengan aman sebelum masalah menjadi tidak terkendali.<br/><br/>Prestasi anda dalam Cyberbullying Management kurang memuaskan dan masih harus dikembangkan.',
        'cyberbullying_d' => 'Management Cyberbullying mengukur kemampuan anda untuk mendeteksi situasi cyberbullying dan menanganinya dengan bijak. <br/>Anda dengan skor Cyberbullying yang tinggi akan : <br/>- Memiliki disiplin pribadi untuk menggunakan media digital secara aman danbertanggung jawab. <br/>- Mengetahui cara mendeteksi situasi ancaman cyber dan cara menangani situasi dengan tenang. <br/>- Mengetahui bagaimana menangani masalah dengan bijaksana dan mencari bantuan dengan aman sebelum masalah menjadi tidak terkendali.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',

        'digital_citizen_identity_a' => 'Digital Citizen Identity; mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Digital Citizen Identity Skill dengan baik.',
        'digital_citizen_identity_b' => 'Digital Citizen Identity; mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Anda telah memahami dengan baik Digital Citizen Identity Skill ! Prestasi anda dalam kategori ini memuaskan.',
        'digital_citizen_identity_c' => 'Digital Citizen Identity; mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Prestasi anda dalam Digital Citizen Identity Skill ini kurang memuaskan dan masih harus dikembangkan.',
        'digital_citizen_identity_d' => 'Digital Citizen Identity; mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',

        'digital_footprint_a' => 'Manajemen Jejak Digital; mengukur kemampuan anda dalam memahami sifat jejak digital, konsekuensinya pada kehidupan nyata dan bagaimana mengelolanya secara bertanggung jawab. <br/>Anda dengan skor Manajemen Jejak Digital yang tinggi akan : <br/>- Memahami sifat komunikasi online dan mengetahui bahwa semua yang dikatakan dan dilakukan secara online akan meninggalkan jejak yang disebut dengan jejak digital. <br/>- Mewaspadai sifat presisten dari jejak digital dan konsekuensinya dalam kehidupan nyata, termasuk menciptakan dampak yang tidak diinginkan pada reputasi online anda. Sebaiknya anda memiliki keterampilan untuk mengelola jejak digital secara bertanggung jawab. mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Digital Footprint Management dengan baik.',
        'digital_footprint_b' => 'Manajemen Jejak Digital; mengukur kemampuan anda dalam memahami sifat jejak digital, konsekuensinya pada kehidupan nyata dan bagaimana mengelolanya secara bertanggung jawab. <br/>Anda dengan skor Manajemen Jejak Digital yang tinggi akan : <br/>- Memahami sifat komunikasi online dan mengetahui bahwa semua yang dikatakan dan dilakukan secara online akan meninggalkan jejak yang disebut dengan jejak digital. <br/>- Mewaspadai sifat presisten dari jejak digital dan konsekuensinya dalam kehidupan nyata, termasuk menciptakan dampak yang tidak diinginkan pada reputasi online anda. Sebaiknya anda memiliki keterampilan untuk mengelola jejak digital secara bertanggung jawab. mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Anda telah memahami dengan baik Digital Footprint Management ! Prestasi anda dalam kategori ini memuaskan.',
        'digital_footprint_c' => 'Manajemen Jejak Digital; mengukur kemampuan anda dalam memahami sifat jejak digital, konsekuensinya pada kehidupan nyata dan bagaimana mengelolanya secara bertanggung jawab. <br/>Anda dengan skor Manajemen Jejak Digital yang tinggi akan : <br/>- Memahami sifat komunikasi online dan mengetahui bahwa semua yang dikatakan dan dilakukan secara online akan meninggalkan jejak yang disebut dengan jejak digital. <br/>- Mewaspadai sifat presisten dari jejak digital dan konsekuensinya dalam kehidupan nyata, termasuk menciptakan dampak yang tidak diinginkan pada reputasi online anda. Sebaiknya anda memiliki keterampilan untuk mengelola jejak digital secara bertanggung jawab. mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Prestasi anda dalam kategori Digital Footprint Management ini kurang memuaskan dan masih harus dikembangkan.',
        'digital_footprint_d' => 'Manajemen Jejak Digital; mengukur kemampuan anda dalam memahami sifat jejak digital, konsekuensinya pada kehidupan nyata dan bagaimana mengelolanya secara bertanggung jawab. <br/>Anda dengan skor Manajemen Jejak Digital yang tinggi akan : <br/>- Memahami sifat komunikasi online dan mengetahui bahwa semua yang dikatakan dan dilakukan secara online akan meninggalkan jejak yang disebut dengan jejak digital. <br/>- Mewaspadai sifat presisten dari jejak digital dan konsekuensinya dalam kehidupan nyata, termasuk menciptakan dampak yang tidak diinginkan pada reputasi online anda. Sebaiknya anda memiliki keterampilan untuk mengelola jejak digital secara bertanggung jawab. mengukur kemampuan anda untuk membangun dan mengelola identitas yang sehat dan berintegritas, baik secara online ataupun offline. <br/>Anda dengan skor Digital Citizen Identity yang tinggi akan : <br/>- Memiliki pemahaman yang sangat baik mengenai cara kerja dunia digital dan dapat menggunakan teknologi dengan percaya diri yang kuat. <br/>- Memiliki pengetahuan dan keterampilan untuk membangun serta mengelola identitas diri yang sehat. <br/>- Menyadari bagaimana menjadi warga negara global yang bertanggung jawab diruang digital.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',

        'cyber_security_management_a' => 'Manajemen Keamanan Cyber; mengukur kemampuan anda dalam melindungi data pribadi dengan membuat kata Sandi yang kuat dan untuk mengelola berbagai serangan di dunia maya, yaitu: SPAM / SCAM /Phishing. <br/>Anda dengan skor manajemen keamanan cyber yang tinggi akan : <br/>- Memiliki kemampuan untuk dapat mengenali serta melindungi diri sendiri dan orang lain dari berbagai serangan dunia maya seperti: Spam/Scam dan Phishing. <br/>- Memiliki keterampilan praktis seperti membuat sandi yang kuat dan mengetahui cara melindungi diri.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Cyber Security Management dengan baik.',
        'cyber_security_management_b' => 'Manajemen Keamanan Cyber; mengukur kemampuan anda dalam melindungi data pribadi dengan membuat kata Sandi yang kuat dan untuk mengelola berbagai serangan di dunia maya, yaitu: SPAM / SCAM /Phishing. <br/>Anda dengan skor manajemen keamanan cyber yang tinggi akan : <br/>- Memiliki kemampuan untuk dapat mengenali serta melindungi diri sendiri dan orang lain dari berbagai serangan dunia maya seperti: Spam/Scam dan Phishing. <br/>- Memiliki keterampilan praktis seperti membuat sandi yang kuat dan mengetahui cara melindungi diri.<br/><br/>Anda telah memahami dengan baik Cyber Security Management ! Prestasi anda dalam kategori ini memuaskan.',
        'cyber_security_management_c' => 'Manajemen Keamanan Cyber; mengukur kemampuan anda dalam melindungi data pribadi dengan membuat kata Sandi yang kuat dan untuk mengelola berbagai serangan di dunia maya, yaitu: SPAM / SCAM /Phishing. <br/>Anda dengan skor manajemen keamanan cyber yang tinggi akan : <br/>- Memiliki kemampuan untuk dapat mengenali serta melindungi diri sendiri dan orang lain dari berbagai serangan dunia maya seperti: Spam/Scam dan Phishing. <br/>- Memiliki keterampilan praktis seperti membuat sandi yang kuat dan mengetahui cara melindungi diri.<br/><br/>Prestasi anda dalam kategori Cyber Security Management ini kurang memuaskan dan masih harus dikembangkan.',
        'cyber_security_management_d' => 'Manajemen Keamanan Cyber; mengukur kemampuan anda dalam melindungi data pribadi dengan membuat kata Sandi yang kuat dan untuk mengelola berbagai serangan di dunia maya, yaitu: SPAM / SCAM /Phishing. <br/>Anda dengan skor manajemen keamanan cyber yang tinggi akan : <br/>- Memiliki kemampuan untuk dapat mengenali serta melindungi diri sendiri dan orang lain dari berbagai serangan dunia maya seperti: Spam/Scam dan Phishing. <br/>- Memiliki keterampilan praktis seperti membuat sandi yang kuat dan mengetahui cara melindungi diri.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',


        'critical_thinking_a' => 'Berpikir Kritis; mengukur kemampuan anda untuk membedakan antara informasi yang benar dan salah, konten yang baik dan berbahaya dan mana kontak online yang dapat dipercaya dan dipertanyakan. <br/>Anda dengan skor berpikir kritis tinggi akan: <br/>- Memiliki pengetahuan serta keterampilan untuk mengevaluasi informasi, konten dan juga kontak di internet dengan bijaksana. <br/>- Memahami efek berbahaya dari informasi palsu, konten kekerasan, konten yang tidak pantas, serta resiko yang terkait dengan teman online. <br/>- Menunjukkan pemikiran yang kritis saat membedakan antara informasi yang benar atau salah, konten yang baik dan berbahaya serta kontak online yang dipercaya atau dipertanyakan.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Critical Thinking Skill dengan baik.',
        'critical_thinking_b' => 'Berpikir Kritis; mengukur kemampuan anda untuk membedakan antara informasi yang benar dan salah, konten yang baik dan berbahaya dan mana kontak online yang dapat dipercaya dan dipertanyakan. <br/>Anda dengan skor berpikir kritis tinggi akan: <br/>- Memiliki pengetahuan serta keterampilan untuk mengevaluasi informasi, konten dan juga kontak di internet dengan bijaksana. <br/>- Memahami efek berbahaya dari informasi palsu, konten kekerasan, konten yang tidak pantas, serta resiko yang terkait dengan teman online. <br/>- Menunjukkan pemikiran yang kritis saat membedakan antara informasi yang benar atau salah, konten yang baik dan berbahaya serta kontak online yang dipercaya atau dipertanyakan.<br/><br/>Anda telah memahami dengan baik Critical Tihinking Skill ! Prestasi anda dalam kategori ini memuaskan.',
        'critical_thinking_c' => 'Berpikir Kritis; mengukur kemampuan anda untuk membedakan antara informasi yang benar dan salah, konten yang baik dan berbahaya dan mana kontak online yang dapat dipercaya dan dipertanyakan. <br/>Anda dengan skor berpikir kritis tinggi akan: <br/>- Memiliki pengetahuan serta keterampilan untuk mengevaluasi informasi, konten dan juga kontak di internet dengan bijaksana. <br/>- Memahami efek berbahaya dari informasi palsu, konten kekerasan, konten yang tidak pantas, serta resiko yang terkait dengan teman online. <br/>- Menunjukkan pemikiran yang kritis saat membedakan antara informasi yang benar atau salah, konten yang baik dan berbahaya serta kontak online yang dipercaya atau dipertanyakan.<br/><br/>Prestasi anda dalam kategori Critical Thinking Skill ini kurang memuaskan dan masih harus dikembangkan.',
        'critical_thinking_d' => 'Berpikir Kritis; mengukur kemampuan anda untuk membedakan antara informasi yang benar dan salah, konten yang baik dan berbahaya dan mana kontak online yang dapat dipercaya dan dipertanyakan. <br/>Anda dengan skor berpikir kritis tinggi akan: <br/>- Memiliki pengetahuan serta keterampilan untuk mengevaluasi informasi, konten dan juga kontak di internet dengan bijaksana. <br/>- Memahami efek berbahaya dari informasi palsu, konten kekerasan, konten yang tidak pantas, serta resiko yang terkait dengan teman online. <br/>- Menunjukkan pemikiran yang kritis saat membedakan antara informasi yang benar atau salah, konten yang baik dan berbahaya serta kontak online yang dipercaya atau dipertanyakan.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',


        'digital_empathy_a' => 'Digital Empathy; mengukur kemampuan anda untuk berempati terhadap kebutuhan dan perasaan diri sendiri serta orang lain secara online. <br/>Anda dengan skor Digital Empathy yang tinggi akan : <br/>- Memiliki kepekaan terhadap kebutuhan dan perasaan diri sendiri serta orang lain saat online bahkan tanpa perlu berinteraksi tatap muka. <br/>- Memiliki kemampuan untuk membangun hubungan yang baik dengan orang tua,guru dan teman secara online maupun offline. <br/>- Menolak pola pikir yang menghakimi secara online dan memiliki keberanian untuk bersuara bagi mereka yang membutuhkan bantuan.<br/><br/>Selamat! performa anda dalam kategori ini sangat baik, terima kasih telah mendukung pemahaman yang kuat tentang Digital Empathy Skill dengan baik.',
        'digital_empathy_b' => 'Digital Empathy; mengukur kemampuan anda untuk berempati terhadap kebutuhan dan perasaan diri sendiri serta orang lain secara online. <br/>Anda dengan skor Digital Empathy yang tinggi akan : <br/>- Memiliki kepekaan terhadap kebutuhan dan perasaan diri sendiri serta orang lain saat online bahkan tanpa perlu berinteraksi tatap muka. <br/>- Memiliki kemampuan untuk membangun hubungan yang baik dengan orang tua,guru dan teman secara online maupun offline. <br/>- Menolak pola pikir yang menghakimi secara online dan memiliki keberanian untuk bersuara bagi mereka yang membutuhkan bantuan.<br/><br/>Anda telah memahami dengan baik Digital Empathy Skill ! Prestasi anda dalam kategori ini memuaskan.',
        'digital_empathy_c' => 'Digital Empathy; mengukur kemampuan anda untuk berempati terhadap kebutuhan dan perasaan diri sendiri serta orang lain secara online. <br/>Anda dengan skor Digital Empathy yang tinggi akan : <br/>- Memiliki kepekaan terhadap kebutuhan dan perasaan diri sendiri serta orang lain saat online bahkan tanpa perlu berinteraksi tatap muka. <br/>- Memiliki kemampuan untuk membangun hubungan yang baik dengan orang tua,guru dan teman secara online maupun offline. <br/>- Menolak pola pikir yang menghakimi secara online dan memiliki keberanian untuk bersuara bagi mereka yang membutuhkan bantuan.<br/><br/>Prestasi anda dalam kategori Digital Empathy Skill ini kurang memuaskan dan masih harus dikembangkan.',
        'digital_empathy_d' => 'Digital Empathy; mengukur kemampuan anda untuk berempati terhadap kebutuhan dan perasaan diri sendiri serta orang lain secara online. <br/>Anda dengan skor Digital Empathy yang tinggi akan : <br/>- Memiliki kepekaan terhadap kebutuhan dan perasaan diri sendiri serta orang lain saat online bahkan tanpa perlu berinteraksi tatap muka. <br/>- Memiliki kemampuan untuk membangun hubungan yang baik dengan orang tua,guru dan teman secara online maupun offline. <br/>- Menolak pola pikir yang menghakimi secara online dan memiliki keberanian untuk bersuara bagi mereka yang membutuhkan bantuan.<br/><br/>Anda belum siap melakukan pengendalian diri saat menggunakan media digital.',
    )
);